apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sumar
  namespace: namespace-jrojas02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: label-sumar
  template:
    metadata:
      labels:
        app: label-sumar
    spec:
      containers:
      - name: container-sumar
        image: jrojas02/service-c-sumar
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
---

apiVersion: v1
kind: Service
metadata:
  name: deployment-sumar
  namespace: namespace-jrojas02
spec:
  selector:
    app: label-sumar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP