apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-calculadora
  namespace: namespace-jrojas
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
