apiVersion: v1
kind: Service
metadata:
  name: service-sql
  namespace: namespace-jrojas02
spec:
  selector:
    app: label-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30000  # Puerto externo que será expuesto en cada nodo
  type: NodePort
