apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-helloword
  namespace: namespace-jrojas02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-helloword
  template:
    metadata:
      labels:
        app: label-helloword
    spec:
      containers:
      - name: container-helloword
        image: jrojas02/service-a-helloword
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  name: service-a-helloword
  namespace: namespace-jrojas02
spec:
  selector:
    app: label-helloword
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
