# app-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-a-helloword
  namespace: namespace-jrojas02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container-a-helloword
  template:
    metadata:
      labels:
        app: container-a-helloword
    spec:
      containers:
      - name: container-a-helloword
        image: jrojas02/service-a-helloword
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: service-a-helloword
  namespace: namespace-jrojas02
spec:
  selector:
    app: container-a-helloword
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
