apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-multiplicar
  namespace: namespace-jrojas02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: label-multiplicar
  template:
    metadata:
      labels:
        app: label-multiplicar
    spec:
      containers:
      - name: container-multiplicar
        image: jrojas02/service-b-multiplicar
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
---

apiVersion: v1
kind: Service
metadata:
  name: service-b-multiplicar
  namespace: namespace-jrojas02
spec:
  selector:
    app: label-multiplicar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
